[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "musicgen-cli"
version = "0.1.0"
description = "raf"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
	"audiocraft",
	"sounddevice",
	"soundfile",
	"torch",
	"transformers",
]	



